version: '3'

services:
  emerging-threats-rules:
    image: mxmd/etr
    build: .
    volumes:
      # our config.json
      - ./config.json:/app/config.json:ro
      # named volume for saving rules
      - nginx-blocking-rules:/app/nginx/conf/
  nginx-blacklist:
    depends_on:
      - emerging-threats-rules
    image: nginx:alpine
    volumes:
      - "nginx-blocking-rules:/etc/nginx/conf.d/"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
volumes:
  nginx-blocking-rules:
