#!/bin/sh

echo "Starting cron job script..."

if [ "$(id -u)" = "0" ]; then
    # Check if the RUN_AS_ROOT environment variable is set to "true"
    if [ "$RUN_AS_ROOT" = "true" ]; then
        echo "Running cron callable as root..."
        /app/nginx_blacklist
    else
        echo "Running cron callable as user anubis..."
        su-exec anubis /app/nginx_blacklist
    fi
else
    if [ "$RUN_AS_ROOT" = "true" ]; then
        echo "RUN_AS_ROOT=true was requested, but cron is running as $(id -un). Running as current user."
    else
        echo "Running cron callable as user $(id -un)..."
    fi
    /app/nginx_blacklist
fi
