name: Build and Release Cross-Platform

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  IMAGE_NAME: mxmd/etr

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test -v ./...

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value={{date 'YYYY-MM-DD-HHmmss'}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: true
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate release tag
        id: release_tag
        if: github.ref == 'refs/heads/master'
        run: |
          TAG="v$(date +'%Y-%m-%d-%H%M%S')"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Generated release tag: $TAG"

      - name: Create Release
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/create-release@v1
        with:
          tag: ${{ steps.release_tag.outputs.tag }}
          name: Release ${{ steps.release_tag.outputs.tag }}
          body: |
            ## Cross-Platform Release ${{ steps.release_tag.outputs.tag }}

            Built from commit: ${{ github.sha }}

            ### Docker Images
            - `${{ env.IMAGE_NAME }}:${{ steps.release_tag.outputs.tag }}`
            - `${{ env.IMAGE_NAME }}:latest`

            ### Docker Multi-Architecture Support
            The Docker image supports:
            - linux/amd64
            - linux/arm64
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
